name: cmd_plus
description: A wrapper around dart:io Process, package:io and mason_logger to
  make it easier to run commands in dart scripts.
version: 1.2.2
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/cmd_plus
issue_tracker: https://github.com/Mankeli-Software/cmd_plus/issues

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  io: ^1.0.4
  mason_logger: ^0.2.5
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: any
  mankeli_analysis: ^1.1.0
  mocktail: ^0.3.0
