name: analysis & test

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
          cache: true


      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify formatting
        run: dart format .

      - name: Analyze project source
        run: flutter analyze . --fatal-infos --no-pub
        
      - name: Test code
        run: flutter test . --no-pub
